# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/events/v1/events.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'bettery/events/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62\x65ttery/events/v1/events.proto\x12\x11\x62\x65ttery.events.v1\"\x9d\x02\n\x06\x45vents\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n\x07\x63reator\x18\x02 \x01(\tR\x07\x63reator\x12\x1a\n\x08question\x18\x03 \x01(\tR\x08question\x12\x18\n\x07\x61nswers\x18\x04 \x03(\tR\x07\x61nswers\x12!\n\x0c\x61nswers_pool\x18\x05 \x03(\x04R\x0b\x61nswersPool\x12\x19\n\x08\x65nd_time\x18\x06 \x01(\x04R\x07\x65ndTime\x12\x1d\n\nstart_time\x18\x07 \x01(\x04R\tstartTime\x12\x1a\n\x08\x63\x61tegory\x18\x08 \x01(\tR\x08\x63\x61tegory\x12\x16\n\x06status\x18\t \x01(\tR\x06status\x12\"\n\x0cparticipants\x18\n \x03(\tR\x0cparticipantsB\xa2\x01\n\x15\x63om.bettery.events.v1B\x0b\x45ventsProtoP\x01Z\x16\x62\x65ttery/x/events/types\xa2\x02\x03\x42\x45X\xaa\x02\x11\x42\x65ttery.Events.V1\xca\x02\x11\x42\x65ttery\\Events\\V1\xe2\x02\x1d\x42\x65ttery\\Events\\V1\\GPBMetadata\xea\x02\x13\x42\x65ttery::Events::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.events.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.bettery.events.v1B\013EventsProtoP\001Z\026bettery/x/events/types\242\002\003BEX\252\002\021Bettery.Events.V1\312\002\021Bettery\\Events\\V1\342\002\035Bettery\\Events\\V1\\GPBMetadata\352\002\023Bettery::Events::V1'
  _globals['_EVENTS']._serialized_start=54
  _globals['_EVENTS']._serialized_end=339
# @@protoc_insertion_point(module_scope)
