# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/events/v1/genesis.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'bettery/events/v1/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from bettery.events.v1 import events_pb2 as bettery_dot_events_dot_v1_dot_events__pb2
from bettery.events.v1 import params_pb2 as bettery_dot_events_dot_v1_dot_params__pb2
from bettery.events.v1 import participant_pb2 as bettery_dot_events_dot_v1_dot_participant__pb2
from bettery.events.v1 import validator_pb2 as bettery_dot_events_dot_v1_dot_validator__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62\x65ttery/events/v1/genesis.proto\x12\x11\x62\x65ttery.events.v1\x1a\x11\x61mino/amino.proto\x1a\x1e\x62\x65ttery/events/v1/events.proto\x1a\x1e\x62\x65ttery/events/v1/params.proto\x1a#bettery/events/v1/participant.proto\x1a!bettery/events/v1/validator.proto\x1a\x14gogoproto/gogo.proto\"\xa3\x03\n\x0cGenesisState\x12<\n\x06params\x18\x01 \x01(\x0b\x32\x19.bettery.events.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\x12@\n\x0b\x65vents_list\x18\x02 \x03(\x0b\x32\x19.bettery.events.v1.EventsB\x04\xc8\xde\x1f\x00R\neventsList\x12!\n\x0c\x65vents_count\x18\x03 \x01(\x04R\x0b\x65ventsCount\x12O\n\x10participant_list\x18\x04 \x03(\x0b\x32\x1e.bettery.events.v1.ParticipantB\x04\xc8\xde\x1f\x00R\x0fparticipantList\x12+\n\x11participant_count\x18\x05 \x01(\x04R\x10participantCount\x12I\n\x0evalidator_list\x18\x06 \x03(\x0b\x32\x1c.bettery.events.v1.ValidatorB\x04\xc8\xde\x1f\x00R\rvalidatorList\x12\'\n\x0fvalidator_count\x18\x07 \x01(\x04R\x0evalidatorCountB\xa3\x01\n\x15\x63om.bettery.events.v1B\x0cGenesisProtoP\x01Z\x16\x62\x65ttery/x/events/types\xa2\x02\x03\x42\x45X\xaa\x02\x11\x42\x65ttery.Events.V1\xca\x02\x11\x42\x65ttery\\Events\\V1\xe2\x02\x1d\x42\x65ttery\\Events\\V1\\GPBMetadata\xea\x02\x13\x42\x65ttery::Events::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.events.v1.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.bettery.events.v1B\014GenesisProtoP\001Z\026bettery/x/events/types\242\002\003BEX\252\002\021Bettery.Events.V1\312\002\021Bettery\\Events\\V1\342\002\035Bettery\\Events\\V1\\GPBMetadata\352\002\023Bettery::Events::V1'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['events_list']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['events_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['participant_list']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['participant_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['validator_list']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['validator_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=232
  _globals['_GENESISSTATE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
