# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/events/v1/genesis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bettery/events/v1/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from bettery.events.v1 import events_pb2 as bettery_dot_events_dot_v1_dot_events__pb2
from bettery.events.v1 import params_pb2 as bettery_dot_events_dot_v1_dot_params__pb2
from bettery.events.v1 import participant_pb2 as bettery_dot_events_dot_v1_dot_participant__pb2
from bettery.events.v1 import validator_pb2 as bettery_dot_events_dot_v1_dot_validator__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62\x65ttery/events/v1/genesis.proto\x12\x11\x62\x65ttery.events.v1\x1a\x11\x61mino/amino.proto\x1a\x1e\x62\x65ttery/events/v1/events.proto\x1a\x1e\x62\x65ttery/events/v1/params.proto\x1a#bettery/events/v1/participant.proto\x1a!bettery/events/v1/validator.proto\x1a\x14gogoproto/gogo.proto\"\xc0\x02\n\x0cGenesisState\x12\x34\n\x06params\x18\x01 \x01(\x0b\x32\x19.bettery.events.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01\x12\x34\n\x0b\x65vents_list\x18\x02 \x03(\x0b\x32\x19.bettery.events.v1.EventsB\x04\xc8\xde\x1f\x00\x12\x14\n\x0c\x65vents_count\x18\x03 \x01(\x04\x12>\n\x10participant_list\x18\x04 \x03(\x0b\x32\x1e.bettery.events.v1.ParticipantB\x04\xc8\xde\x1f\x00\x12\x19\n\x11participant_count\x18\x05 \x01(\x04\x12:\n\x0evalidator_list\x18\x06 \x03(\x0b\x32\x1c.bettery.events.v1.ValidatorB\x04\xc8\xde\x1f\x00\x12\x17\n\x0fvalidator_count\x18\x07 \x01(\x04\x42\x18Z\x16\x62\x65ttery/x/events/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.events.v1.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026bettery/x/events/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['events_list']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['events_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['participant_list']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['participant_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['validator_list']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['validator_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=232
  _globals['_GENESISSTATE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
