# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.bettery.events.v1 import query_pb2 as bettery_dot_events_dot_v1_dot_query__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bettery/events/v1/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryStub(object):
    """Query defines the gRPC querier service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
            '/bettery.events.v1.Query/Params',
            request_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryParamsRequest.SerializeToString,
            response_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryParamsResponse.FromString,
            _registered_method=True)
        self.GetEvents = channel.unary_unary(
            '/bettery.events.v1.Query/GetEvents',
            request_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetEventsRequest.SerializeToString,
            response_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetEventsResponse.FromString,
            _registered_method=True)
        self.ListEvents = channel.unary_unary(
            '/bettery.events.v1.Query/ListEvents',
            request_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllEventsRequest.SerializeToString,
            response_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllEventsResponse.FromString,
            _registered_method=True)
        self.GetParticipant = channel.unary_unary(
            '/bettery.events.v1.Query/GetParticipant',
            request_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetParticipantRequest.SerializeToString,
            response_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetParticipantResponse.FromString,
            _registered_method=True)
        self.ListParticipant = channel.unary_unary(
            '/bettery.events.v1.Query/ListParticipant',
            request_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllParticipantRequest.SerializeToString,
            response_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllParticipantResponse.FromString,
            _registered_method=True)
        self.GetValidator = channel.unary_unary(
            '/bettery.events.v1.Query/GetValidator',
            request_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetValidatorRequest.SerializeToString,
            response_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetValidatorResponse.FromString,
            _registered_method=True)
        self.ListValidator = channel.unary_unary(
            '/bettery.events.v1.Query/ListValidator',
            request_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllValidatorRequest.SerializeToString,
            response_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllValidatorResponse.FromString,
            _registered_method=True)
        self.ListEventsForValidator = channel.unary_unary(
            '/bettery.events.v1.Query/ListEventsForValidator',
            request_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllEventsForValidatorRequest.SerializeToString,
            response_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryEventsForValidatorResponse.FromString,
            _registered_method=True)
        self.ParticipantById = channel.unary_unary(
            '/bettery.events.v1.Query/ParticipantById',
            request_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryParticipantByIdRequest.SerializeToString,
            response_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryParticipantByIdResponse.FromString,
            _registered_method=True)


class QueryServicer(object):
    """Query defines the gRPC querier service.
    """

    def Params(self, request, context):
        """Parameters queries the parameters of the module.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """ListEvents Queries a list of Events items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvents(self, request, context):
        """ListEvents defines the ListEvents RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParticipant(self, request, context):
        """ListParticipant Queries a list of Participant items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListParticipant(self, request, context):
        """ListParticipant defines the ListParticipant RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValidator(self, request, context):
        """ListValidator Queries a list of Validator items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListValidator(self, request, context):
        """ListValidator defines the ListValidator RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEventsForValidator(self, request, context):
        """ListEventsForValidator defines the ListValidator RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParticipantById(self, request, context):
        """ParticipantById Queries a list of ParticipantById items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Params': grpc.unary_unary_rpc_method_handler(
            servicer.Params,
            request_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryParamsRequest.FromString,
            response_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryParamsResponse.SerializeToString,
        ),
        'GetEvents': grpc.unary_unary_rpc_method_handler(
            servicer.GetEvents,
            request_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetEventsRequest.FromString,
            response_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetEventsResponse.SerializeToString,
        ),
        'ListEvents': grpc.unary_unary_rpc_method_handler(
            servicer.ListEvents,
            request_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllEventsRequest.FromString,
            response_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllEventsResponse.SerializeToString,
        ),
        'GetParticipant': grpc.unary_unary_rpc_method_handler(
            servicer.GetParticipant,
            request_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetParticipantRequest.FromString,
            response_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetParticipantResponse.SerializeToString,
        ),
        'ListParticipant': grpc.unary_unary_rpc_method_handler(
            servicer.ListParticipant,
            request_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllParticipantRequest.FromString,
            response_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllParticipantResponse.SerializeToString,
        ),
        'GetValidator': grpc.unary_unary_rpc_method_handler(
            servicer.GetValidator,
            request_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetValidatorRequest.FromString,
            response_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryGetValidatorResponse.SerializeToString,
        ),
        'ListValidator': grpc.unary_unary_rpc_method_handler(
            servicer.ListValidator,
            request_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllValidatorRequest.FromString,
            response_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllValidatorResponse.SerializeToString,
        ),
        'ListEventsForValidator': grpc.unary_unary_rpc_method_handler(
            servicer.ListEventsForValidator,
            request_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryAllEventsForValidatorRequest.FromString,
            response_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryEventsForValidatorResponse.SerializeToString,
        ),
        'ParticipantById': grpc.unary_unary_rpc_method_handler(
            servicer.ParticipantById,
            request_deserializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryParticipantByIdRequest.FromString,
            response_serializer=bettery_dot_events_dot_v1_dot_query__pb2.QueryParticipantByIdResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'bettery.events.v1.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'bettery.events.v1.Query', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class Query(object):
    """Query defines the gRPC querier service.
    """

    @staticmethod
    def Params(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.events.v1.Query/Params',
            bettery_dot_events_dot_v1_dot_query__pb2.QueryParamsRequest.SerializeToString,
            bettery_dot_events_dot_v1_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.events.v1.Query/GetEvents',
            bettery_dot_events_dot_v1_dot_query__pb2.QueryGetEventsRequest.SerializeToString,
            bettery_dot_events_dot_v1_dot_query__pb2.QueryGetEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvents(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.events.v1.Query/ListEvents',
            bettery_dot_events_dot_v1_dot_query__pb2.QueryAllEventsRequest.SerializeToString,
            bettery_dot_events_dot_v1_dot_query__pb2.QueryAllEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParticipant(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.events.v1.Query/GetParticipant',
            bettery_dot_events_dot_v1_dot_query__pb2.QueryGetParticipantRequest.SerializeToString,
            bettery_dot_events_dot_v1_dot_query__pb2.QueryGetParticipantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListParticipant(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.events.v1.Query/ListParticipant',
            bettery_dot_events_dot_v1_dot_query__pb2.QueryAllParticipantRequest.SerializeToString,
            bettery_dot_events_dot_v1_dot_query__pb2.QueryAllParticipantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValidator(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.events.v1.Query/GetValidator',
            bettery_dot_events_dot_v1_dot_query__pb2.QueryGetValidatorRequest.SerializeToString,
            bettery_dot_events_dot_v1_dot_query__pb2.QueryGetValidatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListValidator(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.events.v1.Query/ListValidator',
            bettery_dot_events_dot_v1_dot_query__pb2.QueryAllValidatorRequest.SerializeToString,
            bettery_dot_events_dot_v1_dot_query__pb2.QueryAllValidatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEventsForValidator(request,
                               target,
                               options=(),
                               channel_credentials=None,
                               call_credentials=None,
                               insecure=False,
                               compression=None,
                               wait_for_ready=None,
                               timeout=None,
                               metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.events.v1.Query/ListEventsForValidator',
            bettery_dot_events_dot_v1_dot_query__pb2.QueryAllEventsForValidatorRequest.SerializeToString,
            bettery_dot_events_dot_v1_dot_query__pb2.QueryEventsForValidatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParticipantById(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.events.v1.Query/ParticipantById',
            bettery_dot_events_dot_v1_dot_query__pb2.QueryParticipantByIdRequest.SerializeToString,
            bettery_dot_events_dot_v1_dot_query__pb2.QueryParticipantByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
