# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/events/v1/validator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bettery/events/v1/validator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!bettery/events/v1/validator.proto\x12\x11\x62\x65ttery.events.v1\"\x87\x01\n\tValidator\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x04\x12\x0e\n\x06\x61nswer\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x10\n\x08refunded\x18\x05 \x01(\x08\x12\x16\n\x0e\x63ompany_amount\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\x04\x42\x18Z\x16\x62\x65ttery/x/events/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.events.v1.validator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026bettery/x/events/types'
  _globals['_VALIDATOR']._serialized_start=57
  _globals['_VALIDATOR']._serialized_end=192
# @@protoc_insertion_point(module_scope)
