# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/events/v1/validator.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'bettery/events/v1/validator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!bettery/events/v1/validator.proto\x12\x11\x62\x65ttery.events.v1\"\xc8\x01\n\tValidator\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n\x08\x65vent_id\x18\x02 \x01(\x04R\x07\x65ventId\x12\x16\n\x06\x61nswer\x18\x03 \x01(\tR\x06\x61nswer\x12\x16\n\x06source\x18\x04 \x01(\tR\x06source\x12\x1a\n\x08refunded\x18\x05 \x01(\x08R\x08refunded\x12%\n\x0e\x63ompany_amount\x18\x06 \x01(\tR\rcompanyAmount\x12\x1d\n\ncreated_at\x18\x07 \x01(\x04R\tcreatedAtB\xa5\x01\n\x15\x63om.bettery.events.v1B\x0eValidatorProtoP\x01Z\x16\x62\x65ttery/x/events/types\xa2\x02\x03\x42\x45X\xaa\x02\x11\x42\x65ttery.Events.V1\xca\x02\x11\x42\x65ttery\\Events\\V1\xe2\x02\x1d\x42\x65ttery\\Events\\V1\\GPBMetadata\xea\x02\x13\x42\x65ttery::Events::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.events.v1.validator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.bettery.events.v1B\016ValidatorProtoP\001Z\026bettery/x/events/types\242\002\003BEX\252\002\021Bettery.Events.V1\312\002\021Bettery\\Events\\V1\342\002\035Bettery\\Events\\V1\\GPBMetadata\352\002\023Bettery::Events::V1'
  _globals['_VALIDATOR']._serialized_start=57
  _globals['_VALIDATOR']._serialized_end=257
# @@protoc_insertion_point(module_scope)
