# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cosmos/crypto/bls12_381/keys.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cosmos/crypto/bls12_381/keys.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"cosmos/crypto/bls12_381/keys.proto\x12\x17\x63osmos.crypto.bls12_381\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\"F\n\x06PubKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c:/\x98\xa0\x1f\x00\x8a\xe7\xb0*\x18\x63ometbft/PubKeyBls12_381\x92\xe7\xb0*\tkey_field\"D\n\x07PrivKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c:,\x8a\xe7\xb0*\x19\x63ometbft/PrivKeyBls12_381\x92\xe7\xb0*\tkey_fieldB4Z2github.com/cosmos/cosmos-sdk/crypto/keys/bls12_381b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.crypto.bls12_381.keys_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/cosmos/cosmos-sdk/crypto/keys/bls12_381'
  _globals['_PUBKEY']._loaded_options = None
  _globals['_PUBKEY']._serialized_options = b'\230\240\037\000\212\347\260*\030cometbft/PubKeyBls12_381\222\347\260*\tkey_field'
  _globals['_PRIVKEY']._loaded_options = None
  _globals['_PRIVKEY']._serialized_options = b'\212\347\260*\031cometbft/PrivKeyBls12_381\222\347\260*\tkey_field'
  _globals['_PUBKEY']._serialized_start=104
  _globals['_PUBKEY']._serialized_end=174
  _globals['_PRIVKEY']._serialized_start=176
  _globals['_PRIVKEY']._serialized_end=244
# @@protoc_insertion_point(module_scope)
