# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/funds/v1/params.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'bettery/funds/v1/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x62\x65ttery/funds/v1/params.proto\x12\x10\x62\x65ttery.funds.v1\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\")\n\x06Params:\x1f\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x16\x62\x65ttery/x/funds/ParamsB\x9c\x01\n\x14\x63om.bettery.funds.v1B\x0bParamsProtoP\x01Z\x15\x62\x65ttery/x/funds/types\xa2\x02\x03\x42\x46X\xaa\x02\x10\x42\x65ttery.Funds.V1\xca\x02\x10\x42\x65ttery\\Funds\\V1\xe2\x02\x1c\x42\x65ttery\\Funds\\V1\\GPBMetadata\xea\x02\x12\x42\x65ttery::Funds::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.funds.v1.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.bettery.funds.v1B\013ParamsProtoP\001Z\025bettery/x/funds/types\242\002\003BFX\252\002\020Bettery.Funds.V1\312\002\020Bettery\\Funds\\V1\342\002\034Bettery\\Funds\\V1\\GPBMetadata\352\002\022Bettery::Funds::V1'
  _globals['_PARAMS']._loaded_options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\026bettery/x/funds/Params'
  _globals['_PARAMS']._serialized_start=92
  _globals['_PARAMS']._serialized_end=133
# @@protoc_insertion_point(module_scope)
