# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/funds/v1/query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bettery/funds/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from bettery.funds.v1 import params_pb2 as bettery_dot_funds_dot_v1_dot_params__pb2
from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x62\x65ttery/funds/v1/query.proto\x12\x10\x62\x65ttery.funds.v1\x1a\x11\x61mino/amino.proto\x1a\x1d\x62\x65ttery/funds/v1/params.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n\x12QueryParamsRequest\"J\n\x13QueryParamsResponse\x12\x33\n\x06params\x18\x01 \x01(\x0b\x32\x18.bettery.funds.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01\x32\x80\x01\n\x05Query\x12w\n\x06Params\x12$.bettery.funds.v1.QueryParamsRequest\x1a%.bettery.funds.v1.QueryParamsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/bettery/funds/v1/paramsB\x17Z\x15\x62\x65ttery/x/funds/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.funds.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025bettery/x/funds/types'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._loaded_options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_QUERY'].methods_by_name['Params']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\032\022\030/bettery/funds/v1/params'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=196
  _globals['_QUERYPARAMSREQUEST']._serialized_end=216
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=218
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=292
  _globals['_QUERY']._serialized_start=295
  _globals['_QUERY']._serialized_end=423
# @@protoc_insertion_point(module_scope)
