# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/funds/v1/tx.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'bettery/funds/v1/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from bettery.funds.v1 import params_pb2 as bettery_dot_funds_dot_v1_dot_params__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x62\x65ttery/funds/v1/tx.proto\x12\x10\x62\x65ttery.funds.v1\x1a\x11\x61mino/amino.proto\x1a\x1d\x62\x65ttery/funds/v1/params.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\"\xba\x01\n\x0fMsgUpdateParams\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12;\n\x06params\x18\x02 \x01(\x0b\x32\x18.bettery.funds.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params:2\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*\x1f\x62\x65ttery/x/funds/MsgUpdateParams\"\x19\n\x17MsgUpdateParamsResponse\"l\n\x0cMsgMintToken\x12\x32\n\x07\x63reator\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x07\x63reator\x12\x1a\n\x08receiver\x18\x02 \x01(\tR\x08receiver:\x0c\x82\xe7\xb0*\x07\x63reator\".\n\x14MsgMintTokenResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\"\x83\x01\n\tMintEvent\x12\x18\n\x07\x63reator\x18\x01 \x01(\tR\x07\x63reator\x12\x1a\n\x08receiver\x18\x02 \x01(\tR\x08receiver\x12\x16\n\x06\x61mount\x18\x03 \x01(\tR\x06\x61mount\x12\x14\n\x05token\x18\x04 \x01(\tR\x05token\x12\x12\n\x04time\x18\x05 \x01(\x04R\x04time2\xbf\x01\n\x03Msg\x12\\\n\x0cUpdateParams\x12!.bettery.funds.v1.MsgUpdateParams\x1a).bettery.funds.v1.MsgUpdateParamsResponse\x12S\n\tMintToken\x12\x1e.bettery.funds.v1.MsgMintToken\x1a&.bettery.funds.v1.MsgMintTokenResponse\x1a\x05\x80\xe7\xb0*\x01\x42\x98\x01\n\x14\x63om.bettery.funds.v1B\x07TxProtoP\x01Z\x15\x62\x65ttery/x/funds/types\xa2\x02\x03\x42\x46X\xaa\x02\x10\x42\x65ttery.Funds.V1\xca\x02\x10\x42\x65ttery\\Funds\\V1\xe2\x02\x1c\x42\x65ttery\\Funds\\V1\\GPBMetadata\xea\x02\x12\x42\x65ttery::Funds::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.funds.v1.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.bettery.funds.v1B\007TxProtoP\001Z\025bettery/x/funds/types\242\002\003BFX\252\002\020Bettery.Funds.V1\312\002\020Bettery\\Funds\\V1\342\002\034Bettery\\Funds\\V1\\GPBMetadata\352\002\022Bettery::Funds::V1'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._loaded_options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._loaded_options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._loaded_options = None
  _globals['_MSGUPDATEPARAMS']._serialized_options = b'\202\347\260*\tauthority\212\347\260*\037bettery/x/funds/MsgUpdateParams'
  _globals['_MSGMINTTOKEN'].fields_by_name['creator']._loaded_options = None
  _globals['_MSGMINTTOKEN'].fields_by_name['creator']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGMINTTOKEN']._loaded_options = None
  _globals['_MSGMINTTOKEN']._serialized_options = b'\202\347\260*\007creator'
  _globals['_MSG']._loaded_options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._serialized_start=172
  _globals['_MSGUPDATEPARAMS']._serialized_end=358
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_start=360
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_end=385
  _globals['_MSGMINTTOKEN']._serialized_start=387
  _globals['_MSGMINTTOKEN']._serialized_end=495
  _globals['_MSGMINTTOKENRESPONSE']._serialized_start=497
  _globals['_MSGMINTTOKENRESPONSE']._serialized_end=543
  _globals['_MINTEVENT']._serialized_start=546
  _globals['_MINTEVENT']._serialized_end=677
  _globals['_MSG']._serialized_start=680
  _globals['_MSG']._serialized_end=871
# @@protoc_insertion_point(module_scope)
