# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/guard/v1/genesis.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'bettery/guard/v1/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from bettery.guard.v1 import params_pb2 as bettery_dot_guard_dot_v1_dot_params__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62\x65ttery/guard/v1/genesis.proto\x12\x10\x62\x65ttery.guard.v1\x1a\x11\x61mino/amino.proto\x1a\x1d\x62\x65ttery/guard/v1/params.proto\x1a\x14gogoproto/gogo.proto\"K\n\x0cGenesisState\x12;\n\x06params\x18\x01 \x01(\x0b\x32\x18.bettery.guard.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06paramsB\x9d\x01\n\x14\x63om.bettery.guard.v1B\x0cGenesisProtoP\x01Z\x15\x62\x65ttery/x/guard/types\xa2\x02\x03\x42GX\xaa\x02\x10\x42\x65ttery.Guard.V1\xca\x02\x10\x42\x65ttery\\Guard\\V1\xe2\x02\x1c\x42\x65ttery\\Guard\\V1\\GPBMetadata\xea\x02\x12\x42\x65ttery::Guard::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.guard.v1.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.bettery.guard.v1B\014GenesisProtoP\001Z\025bettery/x/guard/types\242\002\003BGX\252\002\020Bettery.Guard.V1\312\002\020Bettery\\Guard\\V1\342\002\034Bettery\\Guard\\V1\\GPBMetadata\352\002\022Bettery::Guard::V1'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE']._serialized_start=124
  _globals['_GENESISSTATE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
