# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/guard/v1/query.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'bettery/guard/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from bettery.guard.v1 import params_pb2 as bettery_dot_guard_dot_v1_dot_params__pb2
from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x62\x65ttery/guard/v1/query.proto\x12\x10\x62\x65ttery.guard.v1\x1a\x11\x61mino/amino.proto\x1a\x1d\x62\x65ttery/guard/v1/params.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n\x12QueryParamsRequest\"R\n\x13QueryParamsResponse\x12;\n\x06params\x18\x01 \x01(\x0b\x32\x18.bettery.guard.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\"\x16\n\x14QueryGetOwnerRequest\"G\n\x15QueryGetOwnerResponse\x12.\n\x05owner\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x05owner2\x83\x02\n\x05Query\x12w\n\x06Params\x12$.bettery.guard.v1.QueryParamsRequest\x1a%.bettery.guard.v1.QueryParamsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/bettery/guard/v1/params\x12\x80\x01\n\x08GetOwner\x12&.bettery.guard.v1.QueryGetOwnerRequest\x1a\'.bettery.guard.v1.QueryGetOwnerResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/bettery/guard/v1/get_ownerB\x9b\x01\n\x14\x63om.bettery.guard.v1B\nQueryProtoP\x01Z\x15\x62\x65ttery/x/guard/types\xa2\x02\x03\x42GX\xaa\x02\x10\x42\x65ttery.Guard.V1\xca\x02\x10\x42\x65ttery\\Guard\\V1\xe2\x02\x1c\x42\x65ttery\\Guard\\V1\\GPBMetadata\xea\x02\x12\x42\x65ttery::Guard::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.guard.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.bettery.guard.v1B\nQueryProtoP\001Z\025bettery/x/guard/types\242\002\003BGX\252\002\020Bettery.Guard.V1\312\002\020Bettery\\Guard\\V1\342\002\034Bettery\\Guard\\V1\\GPBMetadata\352\002\022Bettery::Guard::V1'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._loaded_options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_QUERYGETOWNERRESPONSE'].fields_by_name['owner']._loaded_options = None
  _globals['_QUERYGETOWNERRESPONSE'].fields_by_name['owner']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_QUERY'].methods_by_name['Params']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\032\022\030/bettery/guard/v1/params'
  _globals['_QUERY'].methods_by_name['GetOwner']._loaded_options = None
  _globals['_QUERY'].methods_by_name['GetOwner']._serialized_options = b'\202\323\344\223\002\035\022\033/bettery/guard/v1/get_owner'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=223
  _globals['_QUERYPARAMSREQUEST']._serialized_end=243
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=245
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=327
  _globals['_QUERYGETOWNERREQUEST']._serialized_start=329
  _globals['_QUERYGETOWNERREQUEST']._serialized_end=351
  _globals['_QUERYGETOWNERRESPONSE']._serialized_start=353
  _globals['_QUERYGETOWNERRESPONSE']._serialized_end=424
  _globals['_QUERY']._serialized_start=427
  _globals['_QUERY']._serialized_end=686
# @@protoc_insertion_point(module_scope)
