# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from bettery.guard.v1 import query_pb2 as bettery_dot_guard_dot_v1_dot_query__pb2


class QueryStub(object):
    """Query defines the gRPC querier service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Params = channel.unary_unary(
                '/bettery.guard.v1.Query/Params',
                request_serializer=bettery_dot_guard_dot_v1_dot_query__pb2.QueryParamsRequest.SerializeToString,
                response_deserializer=bettery_dot_guard_dot_v1_dot_query__pb2.QueryParamsResponse.FromString,
                _registered_method=True)
        self.GetOwner = channel.unary_unary(
                '/bettery.guard.v1.Query/GetOwner',
                request_serializer=bettery_dot_guard_dot_v1_dot_query__pb2.QueryGetOwnerRequest.SerializeToString,
                response_deserializer=bettery_dot_guard_dot_v1_dot_query__pb2.QueryGetOwnerResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Query defines the gRPC querier service.
    """

    def Params(self, request, context):
        """Parameters queries the parameters of the module.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOwner(self, request, context):
        """GetOwner Queries a list of GetOwner items.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Params': grpc.unary_unary_rpc_method_handler(
                    servicer.Params,
                    request_deserializer=bettery_dot_guard_dot_v1_dot_query__pb2.QueryParamsRequest.FromString,
                    response_serializer=bettery_dot_guard_dot_v1_dot_query__pb2.QueryParamsResponse.SerializeToString,
            ),
            'GetOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOwner,
                    request_deserializer=bettery_dot_guard_dot_v1_dot_query__pb2.QueryGetOwnerRequest.FromString,
                    response_serializer=bettery_dot_guard_dot_v1_dot_query__pb2.QueryGetOwnerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bettery.guard.v1.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bettery.guard.v1.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Query defines the gRPC querier service.
    """

    @staticmethod
    def Params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.guard.v1.Query/Params',
            bettery_dot_guard_dot_v1_dot_query__pb2.QueryParamsRequest.SerializeToString,
            bettery_dot_guard_dot_v1_dot_query__pb2.QueryParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.guard.v1.Query/GetOwner',
            bettery_dot_guard_dot_v1_dot_query__pb2.QueryGetOwnerRequest.SerializeToString,
            bettery_dot_guard_dot_v1_dot_query__pb2.QueryGetOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
