# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from bettery.guard.v1 import tx_pb2 as bettery_dot_guard_dot_v1_dot_tx__pb2


class MsgStub(object):
    """Msg defines the Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateParams = channel.unary_unary(
                '/bettery.guard.v1.Msg/UpdateParams',
                request_serializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgUpdateParams.SerializeToString,
                response_deserializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
                _registered_method=True)
        self.SetOwner = channel.unary_unary(
                '/bettery.guard.v1.Msg/SetOwner',
                request_serializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgSetOwner.SerializeToString,
                response_deserializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgSetOwnerResponse.FromString,
                _registered_method=True)
        self.ChangeOwner = channel.unary_unary(
                '/bettery.guard.v1.Msg/ChangeOwner',
                request_serializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgChangeOwner.SerializeToString,
                response_deserializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgChangeOwnerResponse.FromString,
                _registered_method=True)


class MsgServicer(object):
    """Msg defines the Msg service.
    """

    def UpdateParams(self, request, context):
        """UpdateParams defines a (governance) operation for updating the module
        parameters. The authority defaults to the x/gov module account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOwner(self, request, context):
        """SetOwner defines the SetOwner RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeOwner(self, request, context):
        """ChangeOwner defines the ChangeOwner RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateParams': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParams,
                    request_deserializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgUpdateParams.FromString,
                    response_serializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgUpdateParamsResponse.SerializeToString,
            ),
            'SetOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOwner,
                    request_deserializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgSetOwner.FromString,
                    response_serializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgSetOwnerResponse.SerializeToString,
            ),
            'ChangeOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeOwner,
                    request_deserializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgChangeOwner.FromString,
                    response_serializer=bettery_dot_guard_dot_v1_dot_tx__pb2.MsgChangeOwnerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bettery.guard.v1.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bettery.guard.v1.Msg', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the Msg service.
    """

    @staticmethod
    def UpdateParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.guard.v1.Msg/UpdateParams',
            bettery_dot_guard_dot_v1_dot_tx__pb2.MsgUpdateParams.SerializeToString,
            bettery_dot_guard_dot_v1_dot_tx__pb2.MsgUpdateParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.guard.v1.Msg/SetOwner',
            bettery_dot_guard_dot_v1_dot_tx__pb2.MsgSetOwner.SerializeToString,
            bettery_dot_guard_dot_v1_dot_tx__pb2.MsgSetOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bettery.guard.v1.Msg/ChangeOwner',
            bettery_dot_guard_dot_v1_dot_tx__pb2.MsgChangeOwner.SerializeToString,
            bettery_dot_guard_dot_v1_dot_tx__pb2.MsgChangeOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
