# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/guard/v1/tx.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'bettery/guard/v1/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from bettery.guard.v1 import params_pb2 as bettery_dot_guard_dot_v1_dot_params__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x62\x65ttery/guard/v1/tx.proto\x12\x10\x62\x65ttery.guard.v1\x1a\x11\x61mino/amino.proto\x1a\x1d\x62\x65ttery/guard/v1/params.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\"\xba\x01\n\x0fMsgUpdateParams\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12;\n\x06params\x18\x02 \x01(\x0b\x32\x18.bettery.guard.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params:2\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*\x1f\x62\x65ttery/x/guard/MsgUpdateParams\"\x19\n\x17MsgUpdateParamsResponse\"l\n\x0eMsgChangeOwner\x12\x32\n\x07\x63reator\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x07\x63reator\x12\x18\n\x07\x61\x64\x64ress\x18\x02 \x01(\tR\x07\x61\x64\x64ress:\x0c\x82\xe7\xb0*\x07\x63reator\"\x18\n\x16MsgChangeOwnerResponse\"O\n\x0bMsgSetOwner\x12\x32\n\x07\x63reator\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x07\x63reator:\x0c\x82\xe7\xb0*\x07\x63reator\"\x15\n\x13MsgSetOwnerResponse2\x97\x02\n\x03Msg\x12\\\n\x0cUpdateParams\x12!.bettery.guard.v1.MsgUpdateParams\x1a).bettery.guard.v1.MsgUpdateParamsResponse\x12P\n\x08SetOwner\x12\x1d.bettery.guard.v1.MsgSetOwner\x1a%.bettery.guard.v1.MsgSetOwnerResponse\x12Y\n\x0b\x43hangeOwner\x12 .bettery.guard.v1.MsgChangeOwner\x1a(.bettery.guard.v1.MsgChangeOwnerResponse\x1a\x05\x80\xe7\xb0*\x01\x42\x98\x01\n\x14\x63om.bettery.guard.v1B\x07TxProtoP\x01Z\x15\x62\x65ttery/x/guard/types\xa2\x02\x03\x42GX\xaa\x02\x10\x42\x65ttery.Guard.V1\xca\x02\x10\x42\x65ttery\\Guard\\V1\xe2\x02\x1c\x42\x65ttery\\Guard\\V1\\GPBMetadata\xea\x02\x12\x42\x65ttery::Guard::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.guard.v1.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.bettery.guard.v1B\007TxProtoP\001Z\025bettery/x/guard/types\242\002\003BGX\252\002\020Bettery.Guard.V1\312\002\020Bettery\\Guard\\V1\342\002\034Bettery\\Guard\\V1\\GPBMetadata\352\002\022Bettery::Guard::V1'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._loaded_options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._loaded_options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._loaded_options = None
  _globals['_MSGUPDATEPARAMS']._serialized_options = b'\202\347\260*\tauthority\212\347\260*\037bettery/x/guard/MsgUpdateParams'
  _globals['_MSGCHANGEOWNER'].fields_by_name['creator']._loaded_options = None
  _globals['_MSGCHANGEOWNER'].fields_by_name['creator']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGCHANGEOWNER']._loaded_options = None
  _globals['_MSGCHANGEOWNER']._serialized_options = b'\202\347\260*\007creator'
  _globals['_MSGSETOWNER'].fields_by_name['creator']._loaded_options = None
  _globals['_MSGSETOWNER'].fields_by_name['creator']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGSETOWNER']._loaded_options = None
  _globals['_MSGSETOWNER']._serialized_options = b'\202\347\260*\007creator'
  _globals['_MSG']._loaded_options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._serialized_start=172
  _globals['_MSGUPDATEPARAMS']._serialized_end=358
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_start=360
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_end=385
  _globals['_MSGCHANGEOWNER']._serialized_start=387
  _globals['_MSGCHANGEOWNER']._serialized_end=495
  _globals['_MSGCHANGEOWNERRESPONSE']._serialized_start=497
  _globals['_MSGCHANGEOWNERRESPONSE']._serialized_end=521
  _globals['_MSGSETOWNER']._serialized_start=523
  _globals['_MSGSETOWNER']._serialized_end=602
  _globals['_MSGSETOWNERRESPONSE']._serialized_start=604
  _globals['_MSGSETOWNERRESPONSE']._serialized_end=625
  _globals['_MSG']._serialized_start=628
  _globals['_MSG']._serialized_end=907
# @@protoc_insertion_point(module_scope)
