# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cosmos.epochs.v1beta1 import query_pb2 as cosmos_dot_epochs_dot_v1beta1_dot_query__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cosmos/epochs/v1beta1/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryStub(object):
    """Query defines the gRPC querier service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EpochInfos = channel.unary_unary(
                '/cosmos.epochs.v1beta1.Query/EpochInfos',
                request_serializer=cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryEpochInfosRequest.SerializeToString,
                response_deserializer=cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryEpochInfosResponse.FromString,
                _registered_method=True)
        self.CurrentEpoch = channel.unary_unary(
                '/cosmos.epochs.v1beta1.Query/CurrentEpoch',
                request_serializer=cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryCurrentEpochRequest.SerializeToString,
                response_deserializer=cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryCurrentEpochResponse.FromString,
                _registered_method=True)


class QueryServicer(object):
    """Query defines the gRPC querier service.
    """

    def EpochInfos(self, request, context):
        """EpochInfos provide running epochInfos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CurrentEpoch(self, request, context):
        """CurrentEpoch provide current epoch of specified identifier
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EpochInfos': grpc.unary_unary_rpc_method_handler(
                    servicer.EpochInfos,
                    request_deserializer=cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryEpochInfosRequest.FromString,
                    response_serializer=cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryEpochInfosResponse.SerializeToString,
            ),
            'CurrentEpoch': grpc.unary_unary_rpc_method_handler(
                    servicer.CurrentEpoch,
                    request_deserializer=cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryCurrentEpochRequest.FromString,
                    response_serializer=cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryCurrentEpochResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosmos.epochs.v1beta1.Query', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cosmos.epochs.v1beta1.Query', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Query(object):
    """Query defines the gRPC querier service.
    """

    @staticmethod
    def EpochInfos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.epochs.v1beta1.Query/EpochInfos',
            cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryEpochInfosRequest.SerializeToString,
            cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryEpochInfosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CurrentEpoch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cosmos.epochs.v1beta1.Query/CurrentEpoch',
            cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryCurrentEpochRequest.SerializeToString,
            cosmos_dot_epochs_dot_v1beta1_dot_query__pb2.QueryCurrentEpochResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
