# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bettery/events/module/v1/module.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'bettery/events/module/v1/module.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.app.v1alpha1 import module_pb2 as cosmos_dot_app_dot_v1alpha1_dot_module__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%bettery/events/module/v1/module.proto\x12\x18\x62\x65ttery.events.module.v1\x1a cosmos/app/v1alpha1/module.proto\"@\n\x06Module\x12\x1c\n\tauthority\x18\x01 \x01(\tR\tauthority:\x18\xba\xc0\x96\xda\x01\x12\n\x10\x62\x65ttery/x/eventsB\xc6\x01\n\x1c\x63om.bettery.events.module.v1B\x0bModuleProtoP\x01Z\x16\x62\x65ttery/x/events/types\xa2\x02\x03\x42\x45M\xaa\x02\x18\x42\x65ttery.Events.Module.V1\xca\x02\x18\x42\x65ttery\\Events\\Module\\V1\xe2\x02$Bettery\\Events\\Module\\V1\\GPBMetadata\xea\x02\x1b\x42\x65ttery::Events::Module::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bettery.events.module.v1.module_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.bettery.events.module.v1B\013ModuleProtoP\001Z\026bettery/x/events/types\242\002\003BEM\252\002\030Bettery.Events.Module.V1\312\002\030Bettery\\Events\\Module\\V1\342\002$Bettery\\Events\\Module\\V1\\GPBMetadata\352\002\033Bettery::Events::Module::V1'
  _globals['_MODULE']._loaded_options = None
  _globals['_MODULE']._serialized_options = b'\272\300\226\332\001\022\n\020bettery/x/events'
  _globals['_MODULE']._serialized_start=101
  _globals['_MODULE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
